[JS6][arrays-in-details]: homework 1
romashka-dev/prjctr-homeworks pull request #1
Opened 2023-06-11 17:53 UTC by romashka-dev

2023-06-11 19:15 UTC, myroslav-kolomiiets requested changes

2023-06-11 19:15 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_1/index.js
> +initials[0] = "П.О.І.";
Код рішення має проходити по масиву і обробляти його певним чином, для того, щоб отримувати необхідний результат. Тут же хардкод значень.

Рекомендую пригадати методи масивів і рядків, і виконати завдання з їх використанням.

2023-06-11 19:15 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_2/index.js
> +temp = String(temp);
Загалом логіка вірна і рішення робоче, але тут не має необхідності створювати змінні temp та tempReverse. Можна написати лаконічніше.

2023-06-11 19:15 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_3/index.js
> +let temp = resultsArray;
Змінні temp та productOfArray тут не потрібні. Це зайве використання пам'яті.

2023-06-11 19:15 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_3/index.js
> +let getAmountOfArray = getFlatOfArray[0] * getFlatOfArray[1] * getFlatOfArray[2] * getFlatOfArray[3];
Це хардкод. Рішення не має бути специфічне під певний набір даних. Воно має коректно опрацьовувати будь-який масив з цифрами, будь-якої глибини вкладеності.

Для правильного рішення необхідно згадати методи масивів.

2023-06-12 09:28 UTC, romashka-dev commented on src/arrays-in-details/task_1/index.js
> +initials[0] = "П.О.І.";
Не відразу зрозумів, що програма має працювати з різними даними в масиві. Переробив.

2023-06-12 09:28 UTC, romashka-dev commented on src/arrays-in-details/task_2/index.js
> +temp = String(temp);
Підправив.

2023-06-12 09:29 UTC, romashka-dev commented on src/arrays-in-details/task_3/index.js
> +let temp = resultsArray;
Підправив.

2023-06-12 09:29 UTC, romashka-dev commented on src/arrays-in-details/task_3/index.js
> +let getAmountOfArray = getFlatOfArray[0] * getFlatOfArray[1] * getFlatOfArray[2] * getFlatOfArray[3];
Переробив.

2023-06-12 18:24 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_1/index.js
> +
Результат вірний. Але рішення можна зробити з використанням 2-х map замість 4-х. І рекомендую писати виклики методів один за одним, не перезаписуючи змінну initials

2023-06-12 18:25 UTC, myroslav-kolomiiets requested changes

2023-06-12 18:25 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_2/index.js
> +// Задача на розворот числа:
Вірно

2023-06-12 18:25 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_3/index.js
> +productOfArray = productOfArray.flat(2);
Рішення має не залежати від рівня вкладенності тестового масива даних

2023-06-12 18:34 UTC, myroslav-kolomiiets commented on src/arrays-in-details/task_1/index.js
> +initials[0] = "П.О.І.";
В першому варіанті програма не працює з масивом з завдання взагалі)

2023-06-13 13:47 UTC, myroslav-kolomiiets approved these changes

2023-06-13 16:45 UTC, romashka-dev reviewed
This pr has approved by myroslav-kolomiiets

2023-06-13 16:45 UTC, romashka-dev commented on src/arrays-in-details/task_3/index.js
> +productOfArray = productOfArray.flat(2);
Переробив.

2023-06-13 16:45 UTC, romashka-dev commented on src/arrays-in-details/task_2/index.js
> +// Задача на розворот числа:
👌

2023-06-13 16:45 UTC, romashka-dev commented on src/arrays-in-details/task_1/index.js
> +
Переробив.

2023-06-13 18:20 UTC, merged