[objects-and-functions]: homework 2
romashka-dev/prjctr-homeworks pull request #2
Opened 2023-06-16 20:35 UTC by romashka-dev

2023-06-18 20:26 UTC, myroslav-kolomiiets requested changes

2023-06-18 20:26 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +const durationBetweenDates = (dateFrom, dateTo) => {
Функція не приймає розмірність `// — розмірність ('days', 'hours', 'minutes', seconds)`

2023-06-18 20:26 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +        const roundedPrice = parseFloat(data[item]).toFixed(2);
Змінна `roundedPrice` не потрібна, можна зразу: 
```suggestion
        updatedData[lowerCaseKey] = parseFloat(data[item]).toFixed(2);
```

2023-06-20 08:49 UTC, romashka-dev commented on src/objects-and-functions/homework-2.js
> +const durationBetweenDates = (dateFrom, dateTo) => {
Зробив правки в новому коміті.

2023-06-20 08:50 UTC, romashka-dev commented on src/objects-and-functions/homework-2.js
> +        const roundedPrice = parseFloat(data[item]).toFixed(2);
Таким чином, ми зменшили код на одну строку. Зрозумів. Дякую!

2023-06-20 09:35 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +const durationBetweenDates = (dateFrom, dateTo, dimension = 'days') => {
Не задано два параметри за замовчуванням

2023-06-20 09:36 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +        const durationInDays = Math.ceil(timeDiff / (1000 * 60 * 60 * 24));
Математичні операції які виконуються в кожному кейсі, бажано винести кудись в одне місце, наприклад туди, де ви обчислюєте timeDiff

2023-06-20 09:38 UTC, myroslav-kolomiiets requested changes

2023-06-20 09:38 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +// console.log(durationBetweenDates('31 Jan 2022', '03 Feb 2021', 'days')); // поверне '362 days'
Не змінюйте тести що є в завданні) можете доповнити, за бажанням, але залишіть ті що є

2023-06-22 12:47 UTC, romashka-dev commented on src/objects-and-functions/homework-2.js
> +const durationBetweenDates = (dateFrom, dateTo, dimension = 'days') => {
Зробив правки

2023-06-22 12:47 UTC, romashka-dev commented on src/objects-and-functions/homework-2.js
> +        const durationInDays = Math.ceil(timeDiff / (1000 * 60 * 60 * 24));
Зробив правки

2023-06-22 12:47 UTC, romashka-dev commented on src/objects-and-functions/homework-2.js
> +// console.log(durationBetweenDates('31 Jan 2022', '03 Feb 2021', 'days')); // поверне '362 days'
Зробив правки

2023-06-23 12:31 UTC, myroslav-kolomiiets requested changes

2023-06-23 12:31 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +    const durationInSeconds = Math.ceil(timeDiff / 1000);
Якщо в кожному випадку необхідно / 1000, то це варто винести в одне місце, наприклад там де обчислюється timeDiff

2023-06-23 12:31 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
>      if (dimension === 'days') {
Це якраз той випадок де swith зручніше ніж багато if-ів

2023-06-23 12:31 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +console.log(durationBetweenDates('31 Jan 2022', '03 Feb 2021', 'days')); // поверне '362 days'
Бажано залишати всі тести з завдання

2023-06-23 12:31 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +const recursiveOddSumTo = (number, current = 1) => {
Не треба змінювати кількість параметрів функції, вона має приймати один параметр, як вказано в завданні

2023-06-26 19:33 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +        const roundedPrice = parseFloat(data[item]).toFixed(2);
Справа не в зменшенні написаного коду, а в мінус одній, не потрібній більше ніде, змінній

2023-06-26 19:38 UTC, myroslav-kolomiiets requested changes
Додатково - додавайте завжди спочатку 'use strict'

2023-06-26 19:38 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +    const durationInSeconds = Math.ceil(timeDiffSeconds);
Навіщо вам Math.abs і Math.ceil над одними змінними?

2023-06-26 19:38 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +    const oddSumTo = (current) => {
Тут не треба робити внутрішню функцію, можна обійтись однією

2023-06-26 19:38 UTC, myroslav-kolomiiets commented on src/objects-and-functions/homework-2.js
> +// console.log(iterativeOddSumTo(10)) // 25
Перенесення на новий пустий рядок (сам гітхаб показує помилку)

2023-06-28 13:57 UTC, myroslav-kolomiiets approved these changes
Прийнято

2023-06-29 08:35 UTC, merged