[functions-pro-level]: homework 3
romashka-dev/prjctr-homeworks pull request #3
Opened 2023-07-09 07:53 UTC by romashka-dev

2023-07-09 11:09 UTC, myroslav-kolomiiets requested changes

2023-07-09 11:09 UTC, myroslav-kolomiiets commented on src/functions-pro-level/homework-3.js
> +function addThemAll(...args) {
Вірно.

Просто для доповнення, пам'ятайте про reduce

2023-07-09 11:09 UTC, myroslav-kolomiiets commented on src/functions-pro-level/homework-3.js
> +function multiply(a) {
Вірно

2023-07-09 11:09 UTC, myroslav-kolomiiets commented on src/functions-pro-level/homework-3.js
> +function byProperty(property, direction) {
Виконано правильно. Можна спростити переписавши внутрішні if на тернарні оператори, але не обов'язково

2023-07-09 11:09 UTC, myroslav-kolomiiets commented on src/functions-pro-level/homework-3.js
> +    me.intro();
А де тут прив'язка контексту?

2023-07-09 11:13 UTC, myroslav-kolomiiets commented on src/functions-pro-level/homework-3.js
> +    me.intro();
Нагадую про bind/call/apply

2023-07-16 08:36 UTC, romashka-dev commented on src/functions-pro-level/homework-3.js
> +function addThemAll(...args) {
Добре.

2023-07-16 08:37 UTC, romashka-dev commented on src/functions-pro-level/homework-3.js
> +function multiply(a) {
Добре.

2023-07-16 08:37 UTC, romashka-dev commented on src/functions-pro-level/homework-3.js
> +    me.intro();
Виправив.

2023-07-16 14:54 UTC, myroslav-kolomiiets requested changes
6 - зроблено
7 - ні, без неї перевести домашню роботу далі не можу

2023-07-23 19:25 UTC, myroslav-kolomiiets approved these changes

2023-07-27 08:44 UTC, merged