[dom-common-rules]: Homework 4
romashka-dev/prjctr-homeworks pull request #4
Opened 2023-07-27 08:04 UTC by romashka-dev

2023-07-28 11:44 UTC, myroslav-kolomiiets requested changes
Чому не реалізований пункт:

- Стан кнопки та повідомлення останню зміну стану має зберігатись після перезавантаження/закриття сторінки.

?

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            span.innerHTML = `Last turn off: ${turnOffDate.substring(0, 10)}` + ' ' + `${turnOffDate.substring(11, 19)}`;
```suggestion
            span.innerHTML = `Last turn off: ${turnOffDate.substring(0, 10)} ${turnOffDate.substring(11, 19)}`;
```
Ви змішали string interpolation та template literals, з template literals все набагато простіше, почитайте:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            span.innerHTML = `Last turn on: ${turnOnDate.substring(0, 10)}` + ' ' + `${turnOnDate.substring(11, 19)}`;
```suggestion
            span.innerHTML = `Last turn on: ${turnOnDate.substring(0, 10)} ${turnOnDate.substring(11, 19)}`;
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +    const body = document.getElementsByTagName('body');
body один, навіщо використовувати getElementsByTagName? getElementsByTagName поверне нам колекцію, querySelector же сам DOM елемент і не доведеться звертатися до колекції по індексу, щоб взяти з неї єдиний елемент
```suggestion
    const body = document.querySelector('body');
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +    body[0].classList.add('turn-off');
```suggestion
    body.classList.add('turn-off');
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +        if (body[0].classList.contains('turn-off')) {
```suggestion
        if (body.classList.contains('turn-off')) {
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.remove('turn-off');
```suggestion
            body.classList.remove('turn-off');
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.add('turn-on');
```suggestion
            body.classList.add('turn-on');
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.remove('turn-on');
```suggestion
            body.classList.remove('turn-on');
```

2023-07-28 11:44 UTC, myroslav-kolomiiets commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.add('turn-off');
```suggestion
            body.classList.add('turn-off');
```

2023-07-29 14:00 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            span.innerHTML = `Last turn off: ${turnOffDate.substring(0, 10)}` + ' ' + `${turnOffDate.substring(11, 19)}`;
Отже, не треба додавати пробіл, бо користуюсь template literals. Також, не треба змішувати string interpolation та template literals, а використовувати щось одне. Добре. 👍

2023-07-29 14:01 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            span.innerHTML = `Last turn on: ${turnOnDate.substring(0, 10)}` + ' ' + `${turnOnDate.substring(11, 19)}`;
Пофіксив.

2023-07-29 14:04 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +    const body = document.getElementsByTagName('body');
Чомусь подумав, що `document.querySelector` не спрацює для тега body. Бо, мабуть звик, що querySelector має відношення тільки до класів. Виходить, до тегів теж можна звертатись за допомогою `document.querySelector`.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +    body[0].classList.add('turn-off');
Пофіксив.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +        if (body[0].classList.contains('turn-off')) {
Пофіксив.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.remove('turn-off');
Пофіксив.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.add('turn-on');
Пофіксив.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.remove('turn-on');
Пофіксив.

2023-07-29 14:07 UTC, romashka-dev commented on src/dom-common-rules/homework-4-t2.js
> +            body[0].classList.add('turn-off');
Пофіксив.

2023-08-01 14:00 UTC, myroslav-kolomiiets approved these changes

2023-08-09 20:31 UTC, merged