[OOP-in-js]: Homework 5
romashka-dev/prjctr-homeworks pull request #5
Opened 2023-07-30 19:09 UTC by romashka-dev

2023-08-01 14:03 UTC, myroslav-kolomiiets requested changes

2023-08-01 14:03 UTC, myroslav-kolomiiets commented on src/OOP-in-js/homework-5.js
> +      this._privatPropertyCommonRules = 'This is a privat property for class CommonRules';
Чому це приватна властивість?

2023-08-01 14:03 UTC, myroslav-kolomiiets commented on src/OOP-in-js/homework-5.js
> +      return this.phoneNumber;
Цієї властивості немає в конструкторі, власне, немає в класі

2023-08-01 14:03 UTC, myroslav-kolomiiets commented on src/OOP-in-js/homework-5.js
> +        this._privatPropertyCar = 'This is a privat property for class Car';
Тут теж, звідки такий синтаксис?

2023-08-01 14:03 UTC, myroslav-kolomiiets commented on src/OOP-in-js/homework-5.js
> +        this._privatPropertyCar = 'This is a privat property for class Car';
І у всіх інших місцях також

2023-08-06 07:16 UTC, romashka-dev commented on src/OOP-in-js/homework-5.js
> +      this._privatPropertyCommonRules = 'This is a privat property for class CommonRules';
Виправив.

2023-08-06 07:16 UTC, romashka-dev commented on src/OOP-in-js/homework-5.js
> +      return this.phoneNumber;
Додав в конструкторі і передав аргументом в super().

2023-08-06 07:17 UTC, romashka-dev commented on src/OOP-in-js/homework-5.js
> +        this._privatPropertyCar = 'This is a privat property for class Car';
Виправив.

2023-08-07 20:32 UTC, myroslav-kolomiiets approved these changes

2023-08-09 20:32 UTC, merged